name: ci

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    name: Test for node-${{ matrix.node-version }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn install --frozen-lockfile

    - run: |
        yarn workspace fluent-react-components test
        yarn workspace fluent-react-components build
        yarn workspace fluent-react-extract test
        yarn workspace fluent-react-components build
